// Watches the clipboard and keeps the last ten copies, plus the one you're holding.

import AppKit

final class ClipStore {
    private(set) var clips: [Clip] = []
    var limit: Int { max(1, min(10, UserDefaults.standard.integer(forKey: "historySize").nonZero ?? 10)) }
    var secretExpiry: TimeInterval { Double(UserDefaults.standard.integer(forKey: "secretExpirySeconds").nonZero ?? 60) }

    private let pb = NSPasteboard.general
    private var lastCount: Int
    private var ownWrite: Int = -1
    private var timer: Timer?
    var onChange: (() -> Void)?

    private static let concealed = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    private static let skip: Set<String> = ["org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType"]

    init() { lastCount = pb.changeCount }

    func start() {
        timer = Timer.scheduledTimer(withTimeInterval: 0.4, repeats: true) { [weak self] _ in self?.poll() }
        Timer.scheduledTimer(withTimeInterval: 5, repeats: true) { [weak self] _ in self?.expireSecrets() }
    }

    func use(_ clip: Clip, clean: Bool) {
        clip.write(to: pb, clean: clean)
        ownWrite = pb.changeCount
        lastCount = pb.changeCount
        if UserDefaults.standard.bool(forKey: "moveToTopOnPaste"),
           let i = clips.firstIndex(where: { $0 === clip }) { clips.remove(at: i); clips.insert(clip, at: 0) }
        onChange?()
    }

    func clear() { clips.removeAll(); onChange?() }

    private(set) var held: Clip?
    private(set) var heldName = ""

    func hold(_ clip: Clip, name: String) {
        guard !clip.isSecret else { return }
        held = clip
        heldName = name.trimmingCharacters(in: .whitespaces)
        clips.removeAll { $0 === clip }
        onChange?()
    }

    func load(clips: [Clip], held: Clip?, heldName: String) {
        self.clips = clips; self.held = held; self.heldName = heldName; onChange?()
    }

    func rename(_ name: String) { heldName = name.trimmingCharacters(in: .whitespaces); onChange?() }
    func clearHeld() { held = nil; heldName = ""; onChange?() }

    var paused = false
    func resync() { lastCount = pb.changeCount }

    private func poll() {
        guard !paused, pb.changeCount != lastCount else { return }
        lastCount = pb.changeCount
        if lastCount == ownWrite { return }
        let types = Set((pb.types ?? []).map(\.rawValue))
        if !types.isDisjoint(with: Self.skip) { return }
        if types.contains("com.apple.is-remote-clipboard") {
            guard let s = pb.string(forType: .string), !s.isEmpty else { return }
            let front = NSWorkspace.shared.frontmostApplication
            let c = Clip(kind: .text(s), sourceApp: "another Mac", sourceBundle: front?.bundleIdentifier,
                         isSecret: Secrets.looksSecret(s), changeCount: lastCount)
            clips.removeAll { $0.sameContent(as: c) }
            clips.insert(c, at: 0)
            if clips.count > limit { clips.removeLast(clips.count - limit) }
            onChange?()
            return
        }

        let front = NSWorkspace.shared.frontmostApplication
        let app = front?.localizedName ?? "?"
        let bundle = front?.bundleIdentifier
        var clip: Clip?

        let snap = Self.snapshot(pb)
        let imageTypes: Set<String> = ["public.png", "public.tiff", "public.jpeg", "public.heic", "com.compuserve.gif"]
        let hasImage = !types.isDisjoint(with: imageTypes)
        let str = pb.string(forType: .string)

        if let urls = pb.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL], !urls.isEmpty {
            clip = Clip(kind: .files(urls), snapshot: snap, fileThumbnail: Self.thumbnail(of: urls),
                        sourceApp: app, sourceBundle: bundle, isSecret: false, changeCount: lastCount)
        } else if let s = str, !s.isEmpty, let rich = Self.richImages(pb, types: types) {
            clip = Clip(kind: .rich(text: s, images: rich.images, imageCount: rich.count), snapshot: snap,
                        sourceApp: app, sourceBundle: bundle, isSecret: false, changeCount: lastCount)
        } else if hasImage, Self.isJustAnImage(str), let img = NSImage(pasteboard: pb), let tiff = img.tiffRepresentation {
            clip = Clip(kind: .image(tiff), snapshot: snap, sourceApp: app, sourceBundle: bundle,
                        isSecret: false, changeCount: lastCount)
        } else if let s = str, !s.isEmpty {
            let secret = types.contains(Self.concealed.rawValue) || Secrets.looksSecret(s)
            clip = Clip(kind: .text(s), snapshot: secret ? [] : snap, sourceApp: app, sourceBundle: bundle,
                        isSecret: secret, changeCount: lastCount)
        } else if let img = NSImage(pasteboard: pb), let tiff = img.tiffRepresentation {
            clip = Clip(kind: .image(tiff), snapshot: snap, sourceApp: app, sourceBundle: bundle,
                        isSecret: false, changeCount: lastCount)
        }
        guard let c = clip else { return }
        clips.removeAll { $0.sameContent(as: c) }
        clips.insert(c, at: 0)
        if clips.count > limit { clips.removeLast(clips.count - limit) }
        onChange?()
    }

    private func expireSecrets() {
        let now = Date()
        let expired = clips.filter { $0.isSecret && now.timeIntervalSince($0.capturedAt) > secretExpiry }
        guard !expired.isEmpty else { return }
        if let top = clips.first, expired.contains(where: { $0 === top }), pb.changeCount == top.changeCount || pb.changeCount == ownWrite {
            pb.clearContents()
            lastCount = pb.changeCount
        }
        clips.removeAll { c in expired.contains { $0 === c } }
        onChange?()
    }
}

extension ClipStore {
    static func snapshot(_ pb: NSPasteboard) -> [[String: Data]] {
        var total = 0
        var out: [[String: Data]] = []
        for item in pb.pasteboardItems ?? [] {
            var formats: [String: Data] = [:]
            for t in item.types {
                guard let d = item.data(forType: t) else { continue }
                total += d.count
                if total > 40_000_000 { return [] }
                formats[t.rawValue] = d
            }
            out.append(formats)
        }
        return out
    }

    static func richImages(_ pb: NSPasteboard, types: Set<String>) -> (images: [Data], count: Int)? {
        var images: [Data] = []
        var count = 0
        if let notes = pb.data(forType: NSPasteboard.PasteboardType(NotesClip.type)) {
            let pics = NotesClip.images(from: notes)
            if !pics.isEmpty { return (Array(pics.prefix(4)), pics.count) }
        }
        if let rtfd = pb.data(forType: .rtfd) ?? pb.data(forType: NSPasteboard.PasteboardType("com.apple.flat-rtfd")),
           let a = NSAttributedString(rtfd: rtfd, documentAttributes: nil) {
            a.enumerateAttribute(.attachment, in: NSRange(location: 0, length: a.length)) { v, _, _ in
                guard let att = v as? NSTextAttachment else { return }
                count += 1
                if images.count < 4, let d = att.fileWrapper?.regularFileContents, NSImage(data: d) != nil { images.append(d) }
            }
        }
        if count == 0, let html = pb.string(forType: .html) {
            count = html.components(separatedBy: "<img").count - 1
        }
        let items = pb.pasteboardItems ?? []
        if items.count > 1 {
            for item in items where item.types.contains(where: { ["public.png", "public.tiff", "public.jpeg"].contains($0.rawValue) }) {
                count = max(count, 1)
                if images.count < 4, let d = item.data(forType: .png) ?? item.data(forType: .tiff) { images.append(d) }
            }
        }
        return count > 0 && !isJustAnImage(pb.string(forType: .string)) ? (images, count) : nil
    }

    static func isJustAnImage(_ s: String?) -> Bool {
        guard let t = s?.trimmingCharacters(in: .whitespacesAndNewlines), !t.isEmpty else { return true }
        return t.hasPrefix("http") || t.hasPrefix("data:") || (!t.contains("\n") && t.count < 80 && t.split(separator: " ").count <= 6)
    }

    static func thumbnail(of urls: [URL]) -> Data? {
        guard urls.count == 1, let img = NSImage(contentsOf: urls[0]), img.isValid else { return nil }
        let max: CGFloat = 400
        let scale = min(1, max / Swift.max(img.size.width, img.size.height))
        let size = NSSize(width: img.size.width * scale, height: img.size.height * scale)
        let small = NSImage(size: size)
        small.lockFocus(); img.draw(in: NSRect(origin: .zero, size: size)); small.unlockFocus()
        return small.tiffRepresentation
    }
}

extension Int { var nonZero: Int? { self == 0 ? nil : self } }
